# -*- coding: utf-8 -*-
"""Stable-Idle Anomaly Detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PSB3tq_MzBFKXu-GC3DUtkndLjee653q

This code trains an autoencoder to detect unusual OBD-II sensor behavior during **stable idle**. Stable idle means the car is running but not moving, after the initial startup period has settled and the engine is operating relatively steadily. The model learns what healthy stable-idle behavior normally looks like and gives higher reconstruction errors to behavior that differs from what it learned. The model is currently limited to stable idle and cannot diagnose specific mechanical faults. The fake overheating test is only used to check whether the model responds to an obvious abnormal change; it does not prove that the model can detect real overheating.
"""

# Download the carOBD dataset from GitHub (skipped if already present locally).

import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data" / "carOBD"

if not DATA_DIR.exists():
    subprocess.run(
        ["git", "clone", "https://github.com/eron93br/carOBD.git", str(DATA_DIR)],
        check=True
    )

# BLOCK 2 — IMPRT LIBRARIES

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.callbacks import EarlyStopping


# Make results more reproducible. Whenever NumPy or TensorFlow needs random numbers,
# start its random-number generator from seed 42.
np.random.seed(42)
tf.random.set_seed(42)


print("Libraries loaded!")

# BLOCK 3 —  FIND IDLE FILES

data_folder = DATA_DIR / "obdiidata"


idle_files = list(data_folder.glob("idle*.csv"))


# Sort NUMERICALLY: idle1, idle2, idle3... instead of idle1, idle10, idle11...

idle_files = sorted(
    idle_files,
    key=lambda file:
        int(file.stem.replace("idle", ""))
)


print(
    "Number of idle files:",
    len(idle_files)
)


print()

for file in idle_files[:10]:
    print(file.name)

# BLOCK 4 — LOAD AND CLEAN RAW DATA

all_idle_data = []


for file in idle_files:

    # Read one recording.

    current_data = pd.read_csv(
        file,
        skipinitialspace=True,
        index_col=False
    )


    # Clean names like: ENGINE_RPM () -> ENGINE_RPM

    current_data.columns = (
        current_data.columns
        .str.replace(
            " ()",
            "",
            regex=False
        )
    )


    # Fix typo in original dataset.

    current_data = current_data.rename(
        columns={
            "ENGINE_RUN_TINE":
            "ENGINE_RUN_TIME"
        }
    )


    # Remember which recording
    # every row came from.

    current_data["FILE"] = file.name


    all_idle_data.append(current_data)


# Combine all 47 recordings.

idle_data = pd.concat( all_idle_data, ignore_index=True)


print("Total rows:", len(idle_data))

print("Number of recordings:", idle_data["FILE"].nunique())

print("Number of columns:", len(idle_data.columns))


print(idle_data.head())

# BLOCK 5 — CREATE 30-SECOND WINDOWS

# Example:
#
#  0–29 sec  → window 0
# 30–59 sec  → window 1
# 60–89 sec  → window 2


idle_data["WINDOW"] = ( idle_data["ENGINE_RUN_TIME"] // 30).astype(int)


print(
    idle_data[
        [
            "FILE",
            "ENGINE_RUN_TIME",
            "WINDOW",
            "ENGINE_RPM"
        ]
    ].head(20)
)

# BLOCK 6 — REMOVE FINAL WINDOW FROM EACH RECORDING

# The final 30-second window of a recording is often incomplete.
# Find the final window number for each file.

last_window_by_file = (
    idle_data
    .groupby("FILE")["WINDOW"]
    .max()
)


# Give every row its file's final window number.

last_window_for_each_row = (idle_data["FILE"].map(last_window_by_file))


# Keep everything EXCEPT that final window.

idle_data = idle_data[idle_data["WINDOW"] < last_window_for_each_row].copy()


print("Rows remaining:", len(idle_data))

# BLOCK 7 — FIND SENSOR COLUMNS

# These columns identify the recording/window. We DON'T calculate their mean/std.

columns_not_to_summarize = [
    "FILE",
    "WINDOW",
    "ENGINE_RUN_TIME"
]

sensor_columns = []

for column in idle_data.columns:
    if column not in columns_not_to_summarize:
        sensor_columns.append(column)


print("Number of raw sensors:", len(sensor_columns))

print()

for sensor in sensor_columns:
    print(sensor)

# BLOCK 8 — SUMMARIZE EACH WINDOW

# For every sensor in every 30-second windows calculate:
# mean = typical value
# std  = how much it changed


summary = (idle_data.groupby(["FILE", "WINDOW"])[sensor_columns].agg(["mean", "std"]))


print("Number of windows:", len(summary))

# BLOCK 9 — CLEAN SUMMARY COLUMN NAMES

# Clean up the summary table by changing the two-part column names
# (like ("ENGINE_RPM", "mean")) into simple names like "ENGINE_RPM_mean".
# Then turn FILE and WINDOW from index labels back into normal columns.

new_column_names = []

for sensor_name, calculation_name in summary.columns:
    new_name = (sensor_name + "_" + calculation_name)
    new_column_names.append(new_name)


summary.columns = new_column_names

summary = summary.reset_index()

print("Number of windows:", len(summary))

print("Number of columns:", len(summary.columns))


print(summary.head())

# BLOCK 10 — FIND STARTUP / SETTLING WINDOWS

# A very large RPM standard deviation means RPM changed dramatically during the
# 30-second window. Our previous inspection showed startup
# windows around: RPM std = 280–470+ while normal stable windows were usually MUCH lower.


STARTUP_RPM_STD = 200

summary["VERY_UNSTABLE_RPM"] = (summary["ENGINE_RPM_std"] > STARTUP_RPM_STD)


print(
    summary[
        [
            "FILE",
            "WINDOW",
            "ENGINE_RPM_mean",
            "ENGINE_RPM_std",
            "VERY_UNSTABLE_RPM"
        ]
    ].head(30)
)

# BLOCK 11 — FIND START OF STABLE IDLE

startup_windows_to_remove = []

for file in idle_files:

    file_name = file.name

    file_windows = summary[summary["FILE"] == file_name].sort_values("WINDOW")


    # "From this recording, give me only windows whose number is 0, 1, or 2.""

    beginning = file_windows[file_windows["WINDOW"] <= 2]

    unstable_beginning = beginning[beginning["VERY_UNSTABLE_RPM"]]


    # If we found a clearly unstable
    # startup window...

    if len(unstable_beginning) > 0:

        last_unstable_window = (
            unstable_beginning["WINDOW"].max()
        )


        # Remove everything from the
        # beginning THROUGH that window.
        #
        # Example:
        #
        # unstable window = 0
        #
        # remove window 0
        #
        # -----------------
        #
        # unstable windows = 0 and 1
        #
        # remove windows 0 and 1

        windows_to_remove = file_windows[file_windows["WINDOW"] <= last_unstable_window]


        for index in windows_to_remove.index:
            startup_windows_to_remove.append(index)


print("Startup/transition windows identified:", len(startup_windows_to_remove))

# BLOCK 12 — REMOVE STARTUP WINDOWS

windows_before = len(summary)

summary = summary.drop(index=startup_windows_to_remove).copy()

windows_after = len(summary)

print("Windows before:", windows_before)

print("Startup windows removed:", windows_before - windows_after)

print("Stable-idle windows remaining:", windows_after)

# BLOCK 13 — INSPECT STARTUP FILTER

# Just lets us inspect the results and make sure
# the startup filtering didn't do something ridiculous.

removed_startup = (windows_before - windows_after)


print("Removed:", removed_startup, "windows")

print()

print(
    "Remaining RPM mean median:",
    summary["ENGINE_RPM_mean"].median()
)

print(
    "Remaining RPM std median:",
    summary["ENGINE_RPM_std"].median()
)

print(
    "Remaining RPM std 95th percentile:",
    summary["ENGINE_RPM_std"].quantile(0.95)
)

print(
    "Remaining RPM std maximum:",
    summary["ENGINE_RPM_std"].max()
)

# BLOCK 14 — REMOVE HELPER COLUMN

summary = summary.drop( columns=["VERY_UNSTABLE_RPM"])

print("Columns:", len(summary.columns))

# BLOCK 15 — FIND CONSTANT FEATURES

# Find features that have the exact same value in every remaining
# 30-second window. Constant features cannot help the autoencoder
# distinguish between different engine behaviors because they never change.
# FILE and WINDOW are skipped because they are identifiers, not sensor features.
# This block only IDENTIFIES constant features; it does not remove them yet.

all_features = []

for column in summary.columns:
    if column not in ["FILE", "WINDOW"]:
        all_features.append(column)

constant_features = []

for feature in all_features:
    if summary[feature].nunique() <= 1:
        constant_features.append(feature)

print("Starting features:", len(all_features))

print()

print("Constant features:", len(constant_features))

print()

for feature in constant_features:
    print(feature)

# BLOCK 16 — DEFINE NUISANCE FEATURES

nuisance_features = [

    "FUEL_TANK_mean",
    "FUEL_TANK_std",
    "TIME_SINCE_TROUBLE_CODES_CLEARED_mean",
    "TIME_SINCE_TROUBLE_CODES_CLEARED_std",
    "WARM_UPS_SINCE_CODES_CLEARED_mean",
    "WARM_UPS_SINCE_CODES_CLEARED_std"

]


model_features = []

for feature in all_features:

    if (feature not in constant_features and feature not in nuisance_features):
        model_features.append(feature)

print(
    "Starting features:",
    len(all_features)
)

print(
    "Constants removed:",
    len(constant_features)
)

print(
    "Nuisance features removed:",
    len(nuisance_features)
)

print(
    "Final model features:",
    len(model_features)
)

print()


for feature in model_features:
    print(feature)

# BLOCK 17 — CHECK FOR MISSING VALUES

# Check that none of the features we are giving the autoencoder have
# missing values (NaN). The autoencoder needs an actual number for every
# feature in every window. Missing values could cause problems during
# scaling or training, so we check for them before continuing.

missing_values = (summary[model_features].isna().sum())

missing_values = missing_values[missing_values > 0]

if len(missing_values) == 0:
    print("No missing values!")

else:

    print("Features with missing values:")

    print(missing_values)

# BLOCK 18 — SPLIT BY RECORDING

# Split the data into separate training, calibration, and testing sets.
# We split by entire recording (FILE), rather than randomly splitting individual
# windows, so windows from the same recording cannot end up in multiple sets.
# This prevents the model from being tested on data that is very similar to
# data from the exact same recording that it already saw during training.

# Training data: used to teach the autoencoder normal engine behavior.
# Calibration data: used later to help decide what reconstruction error is unusual.
# Testing data: kept separate so we can evaluate the model on unseen recordings.


training_files = [
    f"idle{i}.csv"
    for i in range(1, 34)
]


calibration_files = [
    f"idle{i}.csv"
    for i in range(34, 41)
]


testing_files = [
    f"idle{i}.csv"
    for i in range(41, 48)
]


train_data = summary[
    summary["FILE"].isin(
        training_files
    )
].copy()


calibration_data = summary[
    summary["FILE"].isin(
        calibration_files
    )
].copy()


test_data = summary[
    summary["FILE"].isin(
        testing_files
    )
].copy()


print(
    "Training windows:",
    len(train_data)
)

print(
    "Calibration windows:",
    len(calibration_data)
)

print(
    "Testing windows:",
    len(test_data)
)

# BLOCK 19 — CREATE MODEL INPUTS

# Create the actual input tables that will be used by the autoencoder.
# Each dataset still contains columns like FILE and WINDOW, so we select
# only the sensor features in model_features. Each row is one 30-second
# window and each column is one feature describing that window.

X_train = train_data[model_features].copy()


X_calibration = calibration_data[model_features].copy()

X_test = test_data[model_features].copy()

print("Training:",X_train.shape)

print("Calibration:", X_calibration.shape)

print("Testing:", X_test.shape)

# BLOCK 20 — FINAL DATA CHECK

print(
    "Training missing:",
    X_train.isna().sum().sum()
)

print(
    "Calibration missing:",
    X_calibration.isna().sum().sum()
)

print(
    "Testing missing:",
    X_test.isna().sum().sum()
)

# BLOCK 21 — STANDARDIZE FEATURES

scaler = StandardScaler() # StandardScaler is a tool that will standardize each feature separately.

# IMPORTANT:
# Learn the scaling ONLY from
# the training recordings.

scaler.fit(X_train) # calculates the mean and standard deviation of every feature using X_train
X_train_scaled = scaler.transform(X_train)
X_calibration_scaled = scaler.transform(X_calibration)
X_test_scaled = scaler.transform(X_test)


print(
    "Training mean:",
    np.mean(X_train_scaled)
)

print(
    "Training std:",
    np.std(X_train_scaled)
)

print(
    "NaN:",
    np.isnan(X_train_scaled).any()
)

print(
    "Infinity:",
    np.isinf(X_train_scaled).any()
)

# BLOCK 22 — BUILD AUTOENCODER

number_of_features = (X_train_scaled.shape[1])

autoencoder = Sequential([ # Sequential basically means build a neural network where information travels through these layers one after another.

    Input(shape=(number_of_features,)), # "Each thing I give this neural network will contain 38 numbers."

    Dense(
        24, # This creates a neural-network layer containing 24 neurons.
        activation="relu"
    ),

    # Bottleneck.
    # The model must compress the normal
    # engine behavior into only 8 numbers.

    Dense(
        8,
        activation="relu"
    ),

    Dense(
        24,
        activation="relu"
    ),

    Dense(
        number_of_features,
        activation="linear"
    )

])


autoencoder.summary()

# BLOCK 23 — COMPILE MODEL

autoencoder.compile(optimizer="adam", loss="mse")

# loss="mse" means "Measure how wrong your reconstruction was." ... mse stands for Mean Squared Error.
# Small MSE = reconstruction was good.
# Large MSE = reconstruction was bad.

# optimizer="adam" ... Adam is the algorithm that adjusts those weights during training to try to decrease MSE.

# BLOCK 24 — EARLY STOPPING

# "Keep an eye on how well the model is doing on data it isn't directly training on.
# If it stops improving for 10 epochs, stop training and go back to the best version we saw."

early_stopping = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)

# BLOCK 25 — TRAIN AUTOENCODER

history = autoencoder.fit(

    X_train_scaled,
    X_train_scaled,
    epochs=150,     # "You are allowed to go through all the training data up to 150 times."
    batch_size=32,  # Give the model 32 windows at a time.

    validation_data=(
        X_calibration_scaled,
        X_calibration_scaled
    ),

    callbacks=[early_stopping],

    verbose=1 # Show me the training progress on the screen.
)


print()

print(
    "Epochs trained:",
    len(history.history["loss"])
)

print(
    "Final training loss:",
    history.history["loss"][-1]
)

print(
    "Final validation loss:",
    history.history["val_loss"][-1]
)

print(
    "Best validation loss:",
    min(history.history["val_loss"])
)

# BLOCK 26 — RECONSTRUCT HEALTHY TEST DATA

# "Training is finished. Now give the autoencoder healthy data
# it has never seen before and see what it reconstructs." We;re just
# creating the reconstructed values that we'll need to calculate the anomaly score.

healthy_reconstructed = (autoencoder.predict(X_test_scaled))


print(
    "Original:",
    X_test_scaled.shape
)

print(
    "Reconstructed:",
    healthy_reconstructed.shape
)

# BLOCK 27 — HEALTHY RECONSTRUCTION ERRORS

# Calculate one reconstruction error (anomaly score) for each healthy
# 30-second test window. For each window, compare the 38 actual feature
# values to the 38 values reconstructed by the autoencoder, square the
# differences, and average them. A low error means the model reconstructed
# the window well, while a high error means the window was more unusual.

healthy_errors = np.mean(np.square(X_test_scaled - healthy_reconstructed), axis=1)


print(
    "Number of healthy windows:",
    len(healthy_errors)
)

print(
    "Lowest:",
    np.min(healthy_errors)
)

print(
    "Median:",
    np.median(healthy_errors)
)

print(
    "Average:",
    np.mean(healthy_errors)
)

print(
    "95th percentile:",
    np.percentile(
        healthy_errors,
        95
    )
)

print(
    "99th percentile:",
    np.percentile(
        healthy_errors,
        99
    )
)

print(
    "Highest:",
    np.max(healthy_errors)
)

# BLOCK 28 — CALIBRATION ERRORS

# Calculate reconstruction errors for the healthy calibration windows.
# These errors show the range of reconstruction errors the autoencoder
# produces on normal data. We can later use this distribution to help
# choose an anomaly threshold, while keeping the test data separate for
# final evaluation.

calibration_reconstructed = (autoencoder.predict(X_calibration_scaled))


calibration_errors = np.mean(np.square(X_calibration_scaled - calibration_reconstructed), axis=1)


print(
    "Lowest:",
    np.min(calibration_errors)
)

print(
    "Median:",
    np.median(calibration_errors)
)

print(
    "Average:",
    np.mean(calibration_errors)
)

print(
    "90th percentile:",
    np.percentile(
        calibration_errors,
        90
    )
)

print(
    "95th percentile:",
    np.percentile(
        calibration_errors,
        95
    )
)

print(
    "99th percentile:",
    np.percentile(
        calibration_errors,
        99
    )
)

print(
    "Highest:",
    np.max(calibration_errors)
)

# BLOCK 30 — CREATE FAKE OVERHEATING

# Copy the REAL healthy test windows.

fake_overheating_data = (X_test.copy())

# Change ONLY coolant behavior.

fake_overheating_data["COOLANT_TEMPERATURE_mean"] = 120

fake_overheating_data["COOLANT_TEMPERATURE_std"] = 3


# IMPORTANT:
#
# Use the SAME scaler that learned
# from healthy training data.

# Autoencoder expects standardized numbers, not the original temperatures/RPM/etc.
# So we have to scale this data before giving it to the autoencoder.
fake_overheating_scaled = (scaler.transform(fake_overheating_data))

# BLOCK 31 — RECONSTRUCT OVERHEATING DATA


# We feed the fake overheating windows into our already-trained autoencoder.
overheating_reconstructed = (autoencoder.predict(fake_overheating_scaled))

overheating_errors = np.mean( # This calculates the reconstruction error exactly like we did for the healthy windows:

    np.square(
        fake_overheating_scaled
        -
        overheating_reconstructed
    ),

    axis=1
)

# BLOCK 32 — COMPARE HEALTHY VS OVERHEATING

print("HEALTHY")

print(
    "Lowest:",
    np.min(healthy_errors)
)

print(
    "Median:",
    np.median(healthy_errors)
)

print(
    "Average:",
    np.mean(healthy_errors)
)

print(
    "Highest:",
    np.max(healthy_errors)
)


print()


print("FAKE OVERHEATING")

print(
    "Lowest:",
    np.min(overheating_errors)
)

print(
    "Median:",
    np.median(overheating_errors)
)

print(
    "Average:",
    np.mean(overheating_errors)
)

print(
    "Highest:",
    np.max(overheating_errors)
)

# BLOCK 33 — PAIRED COMPARISON

# Compare each healthy test window with its matching fake overheating
# version. Check whether changing the coolant behavior caused that
# window's reconstruction error to increase. Then count how many windows
# became more unusual and calculate the percentage. This shows how
# consistently the model responds to our simulated overheating change.

became_more_unusual = (overheating_errors > healthy_errors)

number_more_unusual = (became_more_unusual.sum())

percentage_more_unusual = (number_more_unusual / len(healthy_errors) * 100)

print(
    "Windows that became more unusual:",
    number_more_unusual,
    "/",
    len(healthy_errors)
)

print(
    "Percentage:",
    percentage_more_unusual,
    "%"
)